### ISSUE TITLE
iOS & Android Shadow Difference

### ISSUE THREAD

**Issue by WrathChaos** [folofse/androw#11]
Hello,
Thank you so much for Androw. I've been looking for a shadow feature for Android long time. It works awesome however, there is still a difference between iOS and Android. 
Here are the screenshots. 

### Android: 
![Screenshot 2019-08-02 at 12 53 38](https://user-images.githubusercontent.com/6813862/62361986-bdd7d700-b524-11e9-8072-0691b76ead7b.png)

### iOS: 
![Simulator Screen Shot - iPhone X - 2019-08-02 at 12 53 33](https://user-images.githubusercontent.com/6813862/62361994-c0d2c780-b524-11e9-91fe-4a0c8b040bb2.png)

Anyway finally, we have an amazing chance to get shadows on Android. Thank you so much!

**Comment by folofse** [comment]
Thank you for your response! I will look in to this and try to find out how iOS is creating its shadows, I have tried to replicate the html/css way of styling it's shadows like this generator https://www.cssmatic.com/box-shadow. 

The problem might be caused by the dpi difference between how the simulators is representing the pixels, but I'm not 100% sure.

**Comment by WrathChaos** [comment]
Let me try it on the real devices :)

**Comment by WrathChaos** [comment]
@folofse  By the way, if you have a roadmap I would like to help you to develop this project :)

**Comment by folofse** [comment]
@WrathChaos I manage to add pixel density to the Android views and it now matches the iOS device much better. 

I have no road map for this project, I just updates it when I get bug reports, so no special plans for this library in mind at the moment :)

**Comment by WrathChaos** [comment]
@folofse  :) I will this androw on my every project after that. Thank you so much sir :)
