### ISSUE TITLE
Can just set the background View, not all the child views?

### ISSUE THREAD

**Issue by hejun041** [folofse/androw#17]
Like the CardView,not all the items

**Comment by folofse** [comment]
Hi, I suspect that the children are not visible when the bitmap representation of the shadow get created, at the moment the parent gets rendered. I will look in to it.

**Comment by hejun041** [comment]
In my case I use a View to be the first child ,like this:
`
<Androw style={[this.props.style, { backgroundColor: 'transparent' }]}>
<View style={this.props.style}>
{this.props.children}
</View>
</Androw>
`
And you can change the View to Touchable Component

**Comment by folofse** [comment]
Hi sorry for late feedback. It adds the shadow to the nearest child, so if a view is between it will recieve the shadow. I would reccomend you to add Androw on each child that should have the shadow, or in you case on each card.

In this example the shadow gets applied to the view instead of the which lies inside the view.

<img width="456" alt="Screenshot 2020-01-16 at 08 59 50" src="https://user-images.githubusercontent.com/16066712/72504823-e0de1500-383e-11ea-9860-069650c31995.png">

**Comment by hejun041** [comment]
thx a lot
