### ISSUE TITLE
View config not found for name RNAndrow.

### ISSUE THREAD

**Issue by timon2200** [folofse/androw#19]
Invariant Violation: requireNativeComponent:"RNAndrow" was not found in the UIManager when using Expo. 

Does this not work with Expo?

**Comment by folofse** [comment]
It's not currently tested with Expo, I will run some testing during this weekend

**Comment by timon2200** [comment]
Thank you! It would be amazing if this could be fixed!

**Comment by msand** [comment]
Probably only works in bare expo workflow. The managed expo workflow doesn't support adding libraries which have native code in them.

**Comment by folofse** [comment]
Yes, thats correct, you probably have to eject the expo project in order to get it to work.

"Managed Expo projects don't support custom native code, including third-party libraries which require custom native components. In a managed project, you only write JavaScript.
In our SDK, we give you a large set of commonly desired, high-quality native modules. We recommend doing as much in JavaScript as possible, since it can immediately deploy to all your users and work across both platforms, and will always continue to benefit from Expo SDK updates.
However, if you need something custom that isn't possible with the native modules provided in the SDK, like on-the-fly video processing or low-level control over the Bluetooth radio to do a firmware update and other features requested here, you can run expo eject and have full control over the underlying native projects."

https://docs.expo.io/versions/latest/introduction/faq/

**Comment by timon2200** [comment]
Thanks for your response and help!
